[package]
name = "tap_game"
version = "0.1.0"
edition = "2024"

# Configuration des deux binaires exécutables
[[bin]]
name = "tap_server"
path = "src/main.rs"

[[bin]]
name = "tap_cli"
path = "src/cli_main.rs"

[dependencies]
colored = "3.1.1"
eframe = "0.34.3"
egui = "0.34.3"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
tokio-stream = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
rand = "0.8"
chrono = "0.4.45"
